/*
 * @author: Martins Anerua.
 * Martins Anerua © 2018.
 * All rights reserved.
 */
package anerua.safe.software;

import anerua.safe.assembler.Assembler;
import anerua.safe.formatter.Formatter;
import anerua.safe.hardware.DataPath;
import anerua.safe.hardware.Reg;
import anerua.safe.hardware.Registers;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.UIManager;

/**
 * 07-11-2018
 *
 * @author MARTINS
 */
public class BetaUI extends javax.swing.JFrame {

    Registers classReg = new Registers();
    Map<Integer, JScrollPane> panes = new HashMap<>();
    int count = 0;
    
    /**
     * Creates new form BetaUI
     */
    public BetaUI() {
        initComponents();
        
        fileChooser.addChoosableFileFilter(new BetaFileFilter());
        
//        Action buttonAction = new AbstractAction("Run"){
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//            
//        };
//        
//        String key = "Run";
//        
//        btnRun.setAction(buttonAction);
//        
//        btnRun.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), key);
//        
//        btnRun.getActionMap().put(key, buttonAction);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputPane = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        machinePane = new javax.swing.JTextArea();
        editorPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnRun = new javax.swing.JButton();
        btnCompile = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        saveMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        fileChooser.setApproveButtonText("Open");
        fileChooser.setDialogTitle("Open a Beta File");
        fileChooser.setFileHidingEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Beta ISA Machine");
        setExtendedState(Frame.MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setResizeWeight(0.5);

        jSplitPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);
        jSplitPane2.setLastDividerLocation(-1);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane2.setForeground(new java.awt.Color(102, 255, 0));

        outputPane.setEditable(false);
        outputPane.setBackground(new java.awt.Color(204, 204, 204));
        outputPane.setColumns(20);
        outputPane.setForeground(new java.awt.Color(255, 0, 0));
        outputPane.setRows(5);
        outputPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(outputPane);

        jSplitPane2.setLeftComponent(jScrollPane2);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 51))); // NOI18N
        jScrollPane3.setForeground(new java.awt.Color(0, 255, 51));

        machinePane.setEditable(false);
        machinePane.setBackground(new java.awt.Color(153, 153, 255));
        machinePane.setColumns(20);
        machinePane.setRows(5);
        machinePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(machinePane);

        jSplitPane2.setRightComponent(jScrollPane3);

        jSplitPane1.setRightComponent(jSplitPane2);

        editorPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Editor"));
        editorPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setLeftComponent(editorPane);
        editorPane.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 15);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anerua/safe/icons/Run.PNG"))); // NOI18N
        btnRun.setMnemonic(KeyEvent.VK_F5);
        btnRun.setToolTipText("Run (F5)");
        btnRun.setFocusable(false);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        jToolBar2.add(btnRun);

        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anerua/safe/icons/Compile.png"))); // NOI18N
        btnCompile.setToolTipText("Compile");
        btnCompile.setFocusable(false);
        btnCompile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompileActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCompile);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jMenu1.setText("File");

        openMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenu.setText("Open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        jMenu1.add(openMenu);

        saveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenu.setText("Save");
        saveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompileActionPerformed
//        String[] lines = editor.getText().trim().split("\n");
//        
//        Compiler cmp = new Compiler();
//        machinePane.setText("");
//        for(String line: lines){
//            if (!line.trim().equals(""))
//                //System.out.println(line);
//               machinePane.append(cmp.assemble(line) + "\n");
//            //}
//        }
    }//GEN-LAST:event_btnCompileActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // I think it's ambiguous to write this snippet in a UI class
        // Move this code to a non-UI class
        //String source = "";
        String source = ((JTextArea) ((JScrollPane) editorPane.getSelectedComponent()).getViewport().getView()).getText();
        Formatter fm = new Formatter();
        Assembler asm = new Assembler();
        asm.assemblerMain(fm.toStandard(source));
        DataPath dp = new DataPath();
        dp.runCommand(classReg);

        outputPane.setText("");
        for (Reg reg : classReg.registers) {
            outputPane.append("R" + reg.address + " → ");
            outputPane.append(reg.content + "\n");
        }

    }//GEN-LAST:event_btnRunActionPerformed

    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuActionPerformed
        if(fileChooser.showOpenDialog(BetaUI.this) == JFileChooser.APPROVE_OPTION){
            //BufferedReader bf = null;
            String line = "";
            try{
                //System.out.println(fileChooser.getSelectedFile());
                panes.put(++count, new JScrollPane());
                panes.get(count).setViewportView(new JTextArea());
                editorPane.add(fileChooser.getSelectedFile().getName(), panes.get(count));
                
                //System.out.println(fileChooser.getSelectedFile());
                BufferedReader bf = new BufferedReader(new FileReader(fileChooser.getSelectedFile()));
                boolean eof = false;
                while(!eof){
                    try{
                        String cur = bf.readLine();
                        
                        if (!cur.equals(null)){
                            line += cur + "\n";
                            
                        }
                        System.out.println(line);
                    } catch(EOFException e){
                        eof = true;
                    } catch (IOException ex) {
                        Logger.getLogger(BetaUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NullPointerException e){
                        break;
                    }
                    
                }
                
                
            } catch(FileNotFoundException ex){
                Logger.getLogger(BetaUI.class.getName()).log(Level.SEVERE, null, ex);
            } 
//            } finally {
//                try {
//                    bf.close();
//                } catch (IOException ex) {
//                    Logger.getLogger(BetaUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
            ((JTextArea) panes.get(count).getViewport().getView()).append(line);
            editorPane.setSelectedComponent(panes.get(count));
        }
    }//GEN-LAST:event_openMenuActionPerformed

    private void saveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuActionPerformed
        if(fileChooser.showSaveDialog(BetaUI.this) == JFileChooser.APPROVE_OPTION){
            System.out.println(fileChooser.getSelectedFile());
        }
    }//GEN-LAST:event_saveMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BetaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BetaUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton btnRun;
    private javax.swing.JTabbedPane editorPane;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextArea machinePane;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JTextArea outputPane;
    private javax.swing.JMenuItem saveMenu;
    // End of variables declaration//GEN-END:variables
}
